main: su.nightexpress.excellentenchants.EnchantsPlugin
version: '${project.version}'
name: ExcellentEnchants
authors: [ NightExpress, KabanFriends ]
desciption: A lot of new enchantments properly integrated into the server!
api-version: 1.21
load: STARTUP

dependencies:
  server:
    nightcore:
      load: BEFORE
      required: true
    ProtocolLib:
      load: BEFORE
      required: false
    packetevents:
      load: BEFORE
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false
    MythicMobs:
      load: BEFORE
      required: false
